[package]
name = "optikur"
version = "0.1.0"
description = "Optikur: Precision Eye Care & Desktop Wellness Assistant"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["shell-open", "notification-all", "system-tray", "window-hide", "window-show"] }
notify-rust = "=4.11.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "5.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
